### YamlMime:ManagedReference
items:
- uid: R_CrossPlatformSecurity
  commentId: N:R_CrossPlatformSecurity
  id: R_CrossPlatformSecurity
  children:
  - R_CrossPlatformSecurity.R_ISymmetricJSProvider
  - R_CrossPlatformSecurity.R_ISymmetricProvider
  - R_CrossPlatformSecurity.R_SymmetricAesJsProvider
  - R_CrossPlatformSecurity.R_SymmetricAESProvider
  - R_CrossPlatformSecurity.R_SymmetricEnumeration
  langs:
  - csharp
  - vb
  name: R_CrossPlatformSecurity
  nameWithType: R_CrossPlatformSecurity
  fullName: R_CrossPlatformSecurity
  type: Namespace
  assemblies:
  - R_CrossPlatformSecurity
references:
- uid: R_CrossPlatformSecurity.R_ISymmetricJSProvider
  commentId: T:R_CrossPlatformSecurity.R_ISymmetricJSProvider
  parent: R_CrossPlatformSecurity
  name: R_ISymmetricJSProvider
  nameWithType: R_ISymmetricJSProvider
  fullName: R_CrossPlatformSecurity.R_ISymmetricJSProvider
- uid: R_CrossPlatformSecurity.R_ISymmetricProvider
  commentId: T:R_CrossPlatformSecurity.R_ISymmetricProvider
  parent: R_CrossPlatformSecurity
  name: R_ISymmetricProvider
  nameWithType: R_ISymmetricProvider
  fullName: R_CrossPlatformSecurity.R_ISymmetricProvider
- uid: R_CrossPlatformSecurity.R_SymmetricAesJsProvider
  commentId: T:R_CrossPlatformSecurity.R_SymmetricAesJsProvider
  name: R_SymmetricAesJsProvider
  nameWithType: R_SymmetricAesJsProvider
  fullName: R_CrossPlatformSecurity.R_SymmetricAesJsProvider
- uid: R_CrossPlatformSecurity.R_SymmetricAESProvider
  commentId: T:R_CrossPlatformSecurity.R_SymmetricAESProvider
  name: R_SymmetricAESProvider
  nameWithType: R_SymmetricAESProvider
  fullName: R_CrossPlatformSecurity.R_SymmetricAESProvider
- uid: R_CrossPlatformSecurity.R_SymmetricEnumeration
  commentId: T:R_CrossPlatformSecurity.R_SymmetricEnumeration
  name: R_SymmetricEnumeration
  nameWithType: R_SymmetricEnumeration
  fullName: R_CrossPlatformSecurity.R_SymmetricEnumeration
- uid: R_CrossPlatformSecurity
  commentId: N:R_CrossPlatformSecurity
  name: R_CrossPlatformSecurity
  nameWithType: R_CrossPlatformSecurity
  fullName: R_CrossPlatformSecurity
