### YamlMime:ManagedReference
items:
- uid: Serilog.ApplicationBuilderSerilogClientExtensions
  commentId: T:Serilog.ApplicationBuilderSerilogClientExtensions
  id: ApplicationBuilderSerilogClientExtensions
  parent: Serilog
  children:
  - Serilog.ApplicationBuilderSerilogClientExtensions.UseSerilogIngestion(Microsoft.AspNetCore.Builder.IApplicationBuilder,System.Action{Serilog.AspNetCore.Ingestion.SerilogIngestionOptions})
  langs:
  - csharp
  - vb
  name: ApplicationBuilderSerilogClientExtensions
  nameWithType: ApplicationBuilderSerilogClientExtensions
  fullName: Serilog.ApplicationBuilderSerilogClientExtensions
  type: Class
  source:
    remote:
      path: Library Back/Serilog.AspNetCore.Ingestion/ApplicationBuilderSerilogClientExtensions.cs
      branch: master
      repo: git@github.com:siholsihol/RealtaNetCoreLibrary.git
    id: ApplicationBuilderSerilogClientExtensions
    path: Library Back/Serilog.AspNetCore.Ingestion/ApplicationBuilderSerilogClientExtensions.cs
    startLine: 5
  assemblies:
  - Serilog.AspNetCore.Ingestion
  namespace: Serilog
  syntax:
    content: public static class ApplicationBuilderSerilogClientExtensions
    content.vb: Public Module ApplicationBuilderSerilogClientExtensions
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Serilog.ApplicationBuilderSerilogClientExtensions.UseSerilogIngestion(Microsoft.AspNetCore.Builder.IApplicationBuilder,System.Action{Serilog.AspNetCore.Ingestion.SerilogIngestionOptions})
  commentId: M:Serilog.ApplicationBuilderSerilogClientExtensions.UseSerilogIngestion(Microsoft.AspNetCore.Builder.IApplicationBuilder,System.Action{Serilog.AspNetCore.Ingestion.SerilogIngestionOptions})
  id: UseSerilogIngestion(Microsoft.AspNetCore.Builder.IApplicationBuilder,System.Action{Serilog.AspNetCore.Ingestion.SerilogIngestionOptions})
  isExtensionMethod: true
  parent: Serilog.ApplicationBuilderSerilogClientExtensions
  langs:
  - csharp
  - vb
  name: UseSerilogIngestion(IApplicationBuilder, Action<SerilogIngestionOptions>?)
  nameWithType: ApplicationBuilderSerilogClientExtensions.UseSerilogIngestion(IApplicationBuilder, Action<SerilogIngestionOptions>?)
  fullName: Serilog.ApplicationBuilderSerilogClientExtensions.UseSerilogIngestion(Microsoft.AspNetCore.Builder.IApplicationBuilder, System.Action<Serilog.AspNetCore.Ingestion.SerilogIngestionOptions>?)
  type: Method
  source:
    remote:
      path: Library Back/Serilog.AspNetCore.Ingestion/ApplicationBuilderSerilogClientExtensions.cs
      branch: master
      repo: git@github.com:siholsihol/RealtaNetCoreLibrary.git
    id: UseSerilogIngestion
    path: Library Back/Serilog.AspNetCore.Ingestion/ApplicationBuilderSerilogClientExtensions.cs
    startLine: 7
  assemblies:
  - Serilog.AspNetCore.Ingestion
  namespace: Serilog
  syntax:
    content: public static IApplicationBuilder UseSerilogIngestion(this IApplicationBuilder app, Action<SerilogIngestionOptions>? configureOptions = null)
    parameters:
    - id: app
      type: Microsoft.AspNetCore.Builder.IApplicationBuilder
    - id: configureOptions
      type: System.Action{Serilog.AspNetCore.Ingestion.SerilogIngestionOptions}
    return:
      type: Microsoft.AspNetCore.Builder.IApplicationBuilder
    content.vb: Public Shared Function UseSerilogIngestion(app As IApplicationBuilder, configureOptions As Action(Of SerilogIngestionOptions) = Nothing) As IApplicationBuilder
  overload: Serilog.ApplicationBuilderSerilogClientExtensions.UseSerilogIngestion*
  nameWithType.vb: ApplicationBuilderSerilogClientExtensions.UseSerilogIngestion(IApplicationBuilder, Action(Of SerilogIngestionOptions))
  fullName.vb: Serilog.ApplicationBuilderSerilogClientExtensions.UseSerilogIngestion(Microsoft.AspNetCore.Builder.IApplicationBuilder, System.Action(Of Serilog.AspNetCore.Ingestion.SerilogIngestionOptions))
  name.vb: UseSerilogIngestion(IApplicationBuilder, Action(Of SerilogIngestionOptions))
references:
- uid: Serilog
  commentId: N:Serilog
  href: Serilog.html
  name: Serilog
  nameWithType: Serilog
  fullName: Serilog
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Serilog.ApplicationBuilderSerilogClientExtensions.UseSerilogIngestion*
  commentId: Overload:Serilog.ApplicationBuilderSerilogClientExtensions.UseSerilogIngestion
  href: Serilog.ApplicationBuilderSerilogClientExtensions.html#Serilog_ApplicationBuilderSerilogClientExtensions_UseSerilogIngestion_Microsoft_AspNetCore_Builder_IApplicationBuilder_System_Action_Serilog_AspNetCore_Ingestion_SerilogIngestionOptions__
  name: UseSerilogIngestion
  nameWithType: ApplicationBuilderSerilogClientExtensions.UseSerilogIngestion
  fullName: Serilog.ApplicationBuilderSerilogClientExtensions.UseSerilogIngestion
- uid: Microsoft.AspNetCore.Builder.IApplicationBuilder
  commentId: T:Microsoft.AspNetCore.Builder.IApplicationBuilder
  parent: Microsoft.AspNetCore.Builder
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft.aspnetcore.builder.iapplicationbuilder
  name: IApplicationBuilder
  nameWithType: IApplicationBuilder
  fullName: Microsoft.AspNetCore.Builder.IApplicationBuilder
- uid: System.Action{Serilog.AspNetCore.Ingestion.SerilogIngestionOptions}
  commentId: T:System.Action{Serilog.AspNetCore.Ingestion.SerilogIngestionOptions}
  parent: System
  definition: System.Action`1
  href: https://learn.microsoft.com/dotnet/api/system.action-1
  name: Action<SerilogIngestionOptions>
  nameWithType: Action<SerilogIngestionOptions>
  fullName: System.Action<Serilog.AspNetCore.Ingestion.SerilogIngestionOptions>
  nameWithType.vb: Action(Of SerilogIngestionOptions)
  fullName.vb: System.Action(Of Serilog.AspNetCore.Ingestion.SerilogIngestionOptions)
  name.vb: Action(Of SerilogIngestionOptions)
  spec.csharp:
  - uid: System.Action`1
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action-1
  - name: <
  - uid: Serilog.AspNetCore.Ingestion.SerilogIngestionOptions
    name: SerilogIngestionOptions
    href: Serilog.AspNetCore.Ingestion.SerilogIngestionOptions.html
  - name: '>'
  spec.vb:
  - uid: System.Action`1
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action-1
  - name: (
  - name: Of
  - name: " "
  - uid: Serilog.AspNetCore.Ingestion.SerilogIngestionOptions
    name: SerilogIngestionOptions
    href: Serilog.AspNetCore.Ingestion.SerilogIngestionOptions.html
  - name: )
- uid: Microsoft.AspNetCore.Builder
  commentId: N:Microsoft.AspNetCore.Builder
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft
  name: Microsoft.AspNetCore.Builder
  nameWithType: Microsoft.AspNetCore.Builder
  fullName: Microsoft.AspNetCore.Builder
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft
  - name: .
  - uid: Microsoft.AspNetCore
    name: AspNetCore
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.aspnetcore
  - name: .
  - uid: Microsoft.AspNetCore.Builder
    name: Builder
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.aspnetcore.builder
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft
  - name: .
  - uid: Microsoft.AspNetCore
    name: AspNetCore
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.aspnetcore
  - name: .
  - uid: Microsoft.AspNetCore.Builder
    name: Builder
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.aspnetcore.builder
- uid: System.Action`1
  commentId: T:System.Action`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.action-1
  name: Action<T>
  nameWithType: Action<T>
  fullName: System.Action<T>
  nameWithType.vb: Action(Of T)
  fullName.vb: System.Action(Of T)
  name.vb: Action(Of T)
  spec.csharp:
  - uid: System.Action`1
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Action`1
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
