### YamlMime:ManagedReference
items:
- uid: R_BlazorFrontEnd.Deployment.Interfaces
  commentId: N:R_BlazorFrontEnd.Deployment.Interfaces
  id: R_BlazorFrontEnd.Deployment.Interfaces
  children:
  - R_BlazorFrontEnd.Deployment.Interfaces.R_IAssemblyDataProvider
  - R_BlazorFrontEnd.Deployment.Interfaces.R_IAssemblyLoadContext
  - R_BlazorFrontEnd.Deployment.Interfaces.R_IDynamicAssetProviderService
  langs:
  - csharp
  - vb
  name: R_BlazorFrontEnd.Deployment.Interfaces
  nameWithType: R_BlazorFrontEnd.Deployment.Interfaces
  fullName: R_BlazorFrontEnd.Deployment.Interfaces
  type: Namespace
  assemblies:
  - R_BlazorFrontEnd
references:
- uid: R_BlazorFrontEnd.Deployment.Interfaces.R_IAssemblyDataProvider
  commentId: T:R_BlazorFrontEnd.Deployment.Interfaces.R_IAssemblyDataProvider
  parent: R_BlazorFrontEnd.Deployment.Interfaces
  href: R_BlazorFrontEnd.Deployment.Interfaces.R_IAssemblyDataProvider.html
  name: R_IAssemblyDataProvider
  nameWithType: R_IAssemblyDataProvider
  fullName: R_BlazorFrontEnd.Deployment.Interfaces.R_IAssemblyDataProvider
- uid: R_BlazorFrontEnd.Deployment.Interfaces.R_IAssemblyLoadContext
  commentId: T:R_BlazorFrontEnd.Deployment.Interfaces.R_IAssemblyLoadContext
  parent: R_BlazorFrontEnd.Deployment.Interfaces
  href: R_BlazorFrontEnd.Deployment.Interfaces.R_IAssemblyLoadContext.html
  name: R_IAssemblyLoadContext
  nameWithType: R_IAssemblyLoadContext
  fullName: R_BlazorFrontEnd.Deployment.Interfaces.R_IAssemblyLoadContext
- uid: R_BlazorFrontEnd.Deployment.Interfaces.R_IDynamicAssetProviderService
  commentId: T:R_BlazorFrontEnd.Deployment.Interfaces.R_IDynamicAssetProviderService
  parent: R_BlazorFrontEnd.Deployment.Interfaces
  href: R_BlazorFrontEnd.Deployment.Interfaces.R_IDynamicAssetProviderService.html
  name: R_IDynamicAssetProviderService
  nameWithType: R_IDynamicAssetProviderService
  fullName: R_BlazorFrontEnd.Deployment.Interfaces.R_IDynamicAssetProviderService
- uid: R_BlazorFrontEnd.Deployment.Interfaces
  commentId: N:R_BlazorFrontEnd.Deployment.Interfaces
  href: R_BlazorFrontEnd.html
  name: R_BlazorFrontEnd.Deployment.Interfaces
  nameWithType: R_BlazorFrontEnd.Deployment.Interfaces
  fullName: R_BlazorFrontEnd.Deployment.Interfaces
  spec.csharp:
  - uid: R_BlazorFrontEnd
    name: R_BlazorFrontEnd
    href: R_BlazorFrontEnd.html
  - name: .
  - uid: R_BlazorFrontEnd.Deployment
    name: Deployment
    href: R_BlazorFrontEnd.Deployment.html
  - name: .
  - uid: R_BlazorFrontEnd.Deployment.Interfaces
    name: Interfaces
    href: R_BlazorFrontEnd.Deployment.Interfaces.html
  spec.vb:
  - uid: R_BlazorFrontEnd
    name: R_BlazorFrontEnd
    href: R_BlazorFrontEnd.html
  - name: .
  - uid: R_BlazorFrontEnd.Deployment
    name: Deployment
    href: R_BlazorFrontEnd.Deployment.html
  - name: .
  - uid: R_BlazorFrontEnd.Deployment.Interfaces
    name: Interfaces
    href: R_BlazorFrontEnd.Deployment.Interfaces.html
