### YamlMime:ManagedReference
items:
- uid: R_BlazorDeployment.R_IResult
  commentId: T:R_BlazorDeployment.R_IResult
  id: R_IResult
  parent: R_BlazorDeployment
  children:
  - R_BlazorDeployment.R_IResult.Messages
  - R_BlazorDeployment.R_IResult.Succeeded
  langs:
  - csharp
  - vb
  name: R_IResult
  nameWithType: R_IResult
  fullName: R_BlazorDeployment.R_IResult
  type: Interface
  source:
    remote:
      path: Library Back/R_BlazorDeployment/R_IResult.cs
      branch: master
      repo: git@github.com:siholsihol/RealtaNetCoreLibrary.git
    id: R_IResult
    path: Library Back/R_BlazorDeployment/R_IResult.cs
    startLine: 4
  assemblies:
  - R_BlazorDeployment
  namespace: R_BlazorDeployment
  syntax:
    content: public interface R_IResult
    content.vb: Public Interface R_IResult
  extensionMethods:
  - System.Object.R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull
  - System.Object.R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object)
- uid: R_BlazorDeployment.R_IResult.Messages
  commentId: P:R_BlazorDeployment.R_IResult.Messages
  id: Messages
  parent: R_BlazorDeployment.R_IResult
  langs:
  - csharp
  - vb
  name: Messages
  nameWithType: R_IResult.Messages
  fullName: R_BlazorDeployment.R_IResult.Messages
  type: Property
  source:
    remote:
      path: Library Back/R_BlazorDeployment/R_IResult.cs
      branch: master
      repo: git@github.com:siholsihol/RealtaNetCoreLibrary.git
    id: Messages
    path: Library Back/R_BlazorDeployment/R_IResult.cs
    startLine: 6
  assemblies:
  - R_BlazorDeployment
  namespace: R_BlazorDeployment
  syntax:
    content: List<string> Messages { get; set; }
    parameters: []
    return:
      type: System.Collections.Generic.List{System.String}
    content.vb: Property Messages As List(Of String)
  overload: R_BlazorDeployment.R_IResult.Messages*
- uid: R_BlazorDeployment.R_IResult.Succeeded
  commentId: P:R_BlazorDeployment.R_IResult.Succeeded
  id: Succeeded
  parent: R_BlazorDeployment.R_IResult
  langs:
  - csharp
  - vb
  name: Succeeded
  nameWithType: R_IResult.Succeeded
  fullName: R_BlazorDeployment.R_IResult.Succeeded
  type: Property
  source:
    remote:
      path: Library Back/R_BlazorDeployment/R_IResult.cs
      branch: master
      repo: git@github.com:siholsihol/RealtaNetCoreLibrary.git
    id: Succeeded
    path: Library Back/R_BlazorDeployment/R_IResult.cs
    startLine: 7
  assemblies:
  - R_BlazorDeployment
  namespace: R_BlazorDeployment
  syntax:
    content: bool Succeeded { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Property Succeeded As Boolean
  overload: R_BlazorDeployment.R_IResult.Succeeded*
references:
- uid: R_BlazorDeployment
  commentId: N:R_BlazorDeployment
  href: R_BlazorDeployment.html
  name: R_BlazorDeployment
  nameWithType: R_BlazorDeployment
  fullName: R_BlazorDeployment
- uid: System.Object.R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull
  commentId: M:R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
  parent: R_BlazorFrontEnd.Extensions.R_FrontExtensions
  definition: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
  href: R_BlazorFrontEnd.Extensions.R_FrontExtensions.html#R_BlazorFrontEnd_Extensions_R_FrontExtensions_ThrowIfNull_System_Object_
  name: ThrowIfNull(object)
  nameWithType: R_FrontExtensions.ThrowIfNull(object)
  fullName: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(object)
  nameWithType.vb: R_FrontExtensions.ThrowIfNull(Object)
  fullName.vb: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(Object)
  name.vb: ThrowIfNull(Object)
  spec.csharp:
  - uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
    name: ThrowIfNull
    href: R_BlazorFrontEnd.Extensions.R_FrontExtensions.html#R_BlazorFrontEnd_Extensions_R_FrontExtensions_ThrowIfNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
    name: ThrowIfNull
    href: R_BlazorFrontEnd.Extensions.R_FrontExtensions.html#R_BlazorFrontEnd_Extensions_R_FrontExtensions_ThrowIfNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object)
  commentId: M:R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object,System.Object)
  parent: R_BlazorFrontEnd.Helpers.R_FrontUtility
  definition: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object,System.Object)
  href: R_BlazorFrontEnd.Helpers.R_FrontUtility.html#R_BlazorFrontEnd_Helpers_R_FrontUtility_CompareObject_System_Object_System_Object_
  name: CompareObject(object, object)
  nameWithType: R_FrontUtility.CompareObject(object, object)
  fullName: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(object, object)
  nameWithType.vb: R_FrontUtility.CompareObject(Object, Object)
  fullName.vb: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(Object, Object)
  name.vb: CompareObject(Object, Object)
  spec.csharp:
  - uid: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object,System.Object)
    name: CompareObject
    href: R_BlazorFrontEnd.Helpers.R_FrontUtility.html#R_BlazorFrontEnd_Helpers_R_FrontUtility_CompareObject_System_Object_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object,System.Object)
    name: CompareObject
    href: R_BlazorFrontEnd.Helpers.R_FrontUtility.html#R_BlazorFrontEnd_Helpers_R_FrontUtility_CompareObject_System_Object_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
  commentId: M:R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
  isExternal: true
  href: R_BlazorFrontEnd.Extensions.R_FrontExtensions.html#R_BlazorFrontEnd_Extensions_R_FrontExtensions_ThrowIfNull_System_Object_
  name: ThrowIfNull(object)
  nameWithType: R_FrontExtensions.ThrowIfNull(object)
  fullName: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(object)
  nameWithType.vb: R_FrontExtensions.ThrowIfNull(Object)
  fullName.vb: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(Object)
  name.vb: ThrowIfNull(Object)
  spec.csharp:
  - uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
    name: ThrowIfNull
    href: R_BlazorFrontEnd.Extensions.R_FrontExtensions.html#R_BlazorFrontEnd_Extensions_R_FrontExtensions_ThrowIfNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
    name: ThrowIfNull
    href: R_BlazorFrontEnd.Extensions.R_FrontExtensions.html#R_BlazorFrontEnd_Extensions_R_FrontExtensions_ThrowIfNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions
  commentId: T:R_BlazorFrontEnd.Extensions.R_FrontExtensions
  parent: R_BlazorFrontEnd.Extensions
  href: R_BlazorFrontEnd.Extensions.R_FrontExtensions.html
  name: R_FrontExtensions
  nameWithType: R_FrontExtensions
  fullName: R_BlazorFrontEnd.Extensions.R_FrontExtensions
- uid: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object,System.Object)
  commentId: M:R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object,System.Object)
  isExternal: true
  href: R_BlazorFrontEnd.Helpers.R_FrontUtility.html#R_BlazorFrontEnd_Helpers_R_FrontUtility_CompareObject_System_Object_System_Object_
  name: CompareObject(object, object)
  nameWithType: R_FrontUtility.CompareObject(object, object)
  fullName: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(object, object)
  nameWithType.vb: R_FrontUtility.CompareObject(Object, Object)
  fullName.vb: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(Object, Object)
  name.vb: CompareObject(Object, Object)
  spec.csharp:
  - uid: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object,System.Object)
    name: CompareObject
    href: R_BlazorFrontEnd.Helpers.R_FrontUtility.html#R_BlazorFrontEnd_Helpers_R_FrontUtility_CompareObject_System_Object_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object,System.Object)
    name: CompareObject
    href: R_BlazorFrontEnd.Helpers.R_FrontUtility.html#R_BlazorFrontEnd_Helpers_R_FrontUtility_CompareObject_System_Object_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: R_BlazorFrontEnd.Helpers.R_FrontUtility
  commentId: T:R_BlazorFrontEnd.Helpers.R_FrontUtility
  parent: R_BlazorFrontEnd.Helpers
  href: R_BlazorFrontEnd.Helpers.R_FrontUtility.html
  name: R_FrontUtility
  nameWithType: R_FrontUtility
  fullName: R_BlazorFrontEnd.Helpers.R_FrontUtility
- uid: R_BlazorFrontEnd.Extensions
  commentId: N:R_BlazorFrontEnd.Extensions
  href: R_BlazorFrontEnd.html
  name: R_BlazorFrontEnd.Extensions
  nameWithType: R_BlazorFrontEnd.Extensions
  fullName: R_BlazorFrontEnd.Extensions
  spec.csharp:
  - uid: R_BlazorFrontEnd
    name: R_BlazorFrontEnd
    href: R_BlazorFrontEnd.html
  - name: .
  - uid: R_BlazorFrontEnd.Extensions
    name: Extensions
    href: R_BlazorFrontEnd.Extensions.html
  spec.vb:
  - uid: R_BlazorFrontEnd
    name: R_BlazorFrontEnd
    href: R_BlazorFrontEnd.html
  - name: .
  - uid: R_BlazorFrontEnd.Extensions
    name: Extensions
    href: R_BlazorFrontEnd.Extensions.html
- uid: R_BlazorFrontEnd.Helpers
  commentId: N:R_BlazorFrontEnd.Helpers
  href: R_BlazorFrontEnd.html
  name: R_BlazorFrontEnd.Helpers
  nameWithType: R_BlazorFrontEnd.Helpers
  fullName: R_BlazorFrontEnd.Helpers
  spec.csharp:
  - uid: R_BlazorFrontEnd
    name: R_BlazorFrontEnd
    href: R_BlazorFrontEnd.html
  - name: .
  - uid: R_BlazorFrontEnd.Helpers
    name: Helpers
    href: R_BlazorFrontEnd.Helpers.html
  spec.vb:
  - uid: R_BlazorFrontEnd
    name: R_BlazorFrontEnd
    href: R_BlazorFrontEnd.html
  - name: .
  - uid: R_BlazorFrontEnd.Helpers
    name: Helpers
    href: R_BlazorFrontEnd.Helpers.html
- uid: R_BlazorDeployment.R_IResult.Messages*
  commentId: Overload:R_BlazorDeployment.R_IResult.Messages
  href: R_BlazorDeployment.R_IResult.html#R_BlazorDeployment_R_IResult_Messages
  name: Messages
  nameWithType: R_IResult.Messages
  fullName: R_BlazorDeployment.R_IResult.Messages
- uid: System.Collections.Generic.List{System.String}
  commentId: T:System.Collections.Generic.List{System.String}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<string>
  nameWithType: List<string>
  fullName: System.Collections.Generic.List<string>
  nameWithType.vb: List(Of String)
  fullName.vb: System.Collections.Generic.List(Of String)
  name.vb: List(Of String)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: R_BlazorDeployment.R_IResult.Succeeded*
  commentId: Overload:R_BlazorDeployment.R_IResult.Succeeded
  href: R_BlazorDeployment.R_IResult.html#R_BlazorDeployment_R_IResult_Succeeded
  name: Succeeded
  nameWithType: R_IResult.Succeeded
  fullName: R_BlazorDeployment.R_IResult.Succeeded
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
