### YamlMime:ManagedReference
items:
- uid: R_BlazorDeployment.R_IResult`1
  commentId: T:R_BlazorDeployment.R_IResult`1
  id: R_IResult`1
  parent: R_BlazorDeployment
  children:
  - R_BlazorDeployment.R_IResult`1.Data
  langs:
  - csharp
  - vb
  name: R_IResult<T>
  nameWithType: R_IResult<T>
  fullName: R_BlazorDeployment.R_IResult<T>
  type: Interface
  source:
    remote:
      path: Library Back/R_BlazorDeployment/R_IResult.cs
      branch: master
      repo: git@github.com:siholsihol/RealtaNetCoreLibrary.git
    id: R_IResult
    path: Library Back/R_BlazorDeployment/R_IResult.cs
    startLine: 10
  assemblies:
  - R_BlazorDeployment
  namespace: R_BlazorDeployment
  syntax:
    content: 'public interface R_IResult<out T> : R_IResult'
    typeParameters:
    - id: T
    content.vb: Public Interface R_IResult(Of Out T) Inherits R_IResult
  inheritedMembers:
  - R_BlazorDeployment.R_IResult.Messages
  - R_BlazorDeployment.R_IResult.Succeeded
  extensionMethods:
  - System.Object.R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull
  - System.Object.R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object)
  nameWithType.vb: R_IResult(Of T)
  fullName.vb: R_BlazorDeployment.R_IResult(Of T)
  name.vb: R_IResult(Of T)
- uid: R_BlazorDeployment.R_IResult`1.Data
  commentId: P:R_BlazorDeployment.R_IResult`1.Data
  id: Data
  parent: R_BlazorDeployment.R_IResult`1
  langs:
  - csharp
  - vb
  name: Data
  nameWithType: R_IResult<T>.Data
  fullName: R_BlazorDeployment.R_IResult<T>.Data
  type: Property
  source:
    remote:
      path: Library Back/R_BlazorDeployment/R_IResult.cs
      branch: master
      repo: git@github.com:siholsihol/RealtaNetCoreLibrary.git
    id: Data
    path: Library Back/R_BlazorDeployment/R_IResult.cs
    startLine: 12
  assemblies:
  - R_BlazorDeployment
  namespace: R_BlazorDeployment
  syntax:
    content: T? Data { get; }
    parameters: []
    return:
      type: '{T}'
    content.vb: ReadOnly Property Data As T
  overload: R_BlazorDeployment.R_IResult`1.Data*
  nameWithType.vb: R_IResult(Of T).Data
  fullName.vb: R_BlazorDeployment.R_IResult(Of T).Data
references:
- uid: R_BlazorDeployment
  commentId: N:R_BlazorDeployment
  href: R_BlazorDeployment.html
  name: R_BlazorDeployment
  nameWithType: R_BlazorDeployment
  fullName: R_BlazorDeployment
- uid: R_BlazorDeployment.R_IResult.Messages
  commentId: P:R_BlazorDeployment.R_IResult.Messages
  parent: R_BlazorDeployment.R_IResult
  href: R_BlazorDeployment.R_IResult.html#R_BlazorDeployment_R_IResult_Messages
  name: Messages
  nameWithType: R_IResult.Messages
  fullName: R_BlazorDeployment.R_IResult.Messages
- uid: R_BlazorDeployment.R_IResult.Succeeded
  commentId: P:R_BlazorDeployment.R_IResult.Succeeded
  parent: R_BlazorDeployment.R_IResult
  href: R_BlazorDeployment.R_IResult.html#R_BlazorDeployment_R_IResult_Succeeded
  name: Succeeded
  nameWithType: R_IResult.Succeeded
  fullName: R_BlazorDeployment.R_IResult.Succeeded
- uid: System.Object.R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull
  commentId: M:R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
  parent: R_BlazorFrontEnd.Extensions.R_FrontExtensions
  definition: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
  href: R_BlazorFrontEnd.Extensions.R_FrontExtensions.html#R_BlazorFrontEnd_Extensions_R_FrontExtensions_ThrowIfNull_System_Object_
  name: ThrowIfNull(object)
  nameWithType: R_FrontExtensions.ThrowIfNull(object)
  fullName: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(object)
  nameWithType.vb: R_FrontExtensions.ThrowIfNull(Object)
  fullName.vb: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(Object)
  name.vb: ThrowIfNull(Object)
  spec.csharp:
  - uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
    name: ThrowIfNull
    href: R_BlazorFrontEnd.Extensions.R_FrontExtensions.html#R_BlazorFrontEnd_Extensions_R_FrontExtensions_ThrowIfNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
    name: ThrowIfNull
    href: R_BlazorFrontEnd.Extensions.R_FrontExtensions.html#R_BlazorFrontEnd_Extensions_R_FrontExtensions_ThrowIfNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object)
  commentId: M:R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object,System.Object)
  parent: R_BlazorFrontEnd.Helpers.R_FrontUtility
  definition: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object,System.Object)
  href: R_BlazorFrontEnd.Helpers.R_FrontUtility.html#R_BlazorFrontEnd_Helpers_R_FrontUtility_CompareObject_System_Object_System_Object_
  name: CompareObject(object, object)
  nameWithType: R_FrontUtility.CompareObject(object, object)
  fullName: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(object, object)
  nameWithType.vb: R_FrontUtility.CompareObject(Object, Object)
  fullName.vb: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(Object, Object)
  name.vb: CompareObject(Object, Object)
  spec.csharp:
  - uid: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object,System.Object)
    name: CompareObject
    href: R_BlazorFrontEnd.Helpers.R_FrontUtility.html#R_BlazorFrontEnd_Helpers_R_FrontUtility_CompareObject_System_Object_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object,System.Object)
    name: CompareObject
    href: R_BlazorFrontEnd.Helpers.R_FrontUtility.html#R_BlazorFrontEnd_Helpers_R_FrontUtility_CompareObject_System_Object_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: R_BlazorDeployment.R_IResult
  commentId: T:R_BlazorDeployment.R_IResult
  parent: R_BlazorDeployment
  href: R_BlazorDeployment.R_IResult.html
  name: R_IResult
  nameWithType: R_IResult
  fullName: R_BlazorDeployment.R_IResult
- uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
  commentId: M:R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
  isExternal: true
  href: R_BlazorFrontEnd.Extensions.R_FrontExtensions.html#R_BlazorFrontEnd_Extensions_R_FrontExtensions_ThrowIfNull_System_Object_
  name: ThrowIfNull(object)
  nameWithType: R_FrontExtensions.ThrowIfNull(object)
  fullName: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(object)
  nameWithType.vb: R_FrontExtensions.ThrowIfNull(Object)
  fullName.vb: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(Object)
  name.vb: ThrowIfNull(Object)
  spec.csharp:
  - uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
    name: ThrowIfNull
    href: R_BlazorFrontEnd.Extensions.R_FrontExtensions.html#R_BlazorFrontEnd_Extensions_R_FrontExtensions_ThrowIfNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
    name: ThrowIfNull
    href: R_BlazorFrontEnd.Extensions.R_FrontExtensions.html#R_BlazorFrontEnd_Extensions_R_FrontExtensions_ThrowIfNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions
  commentId: T:R_BlazorFrontEnd.Extensions.R_FrontExtensions
  parent: R_BlazorFrontEnd.Extensions
  href: R_BlazorFrontEnd.Extensions.R_FrontExtensions.html
  name: R_FrontExtensions
  nameWithType: R_FrontExtensions
  fullName: R_BlazorFrontEnd.Extensions.R_FrontExtensions
- uid: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object,System.Object)
  commentId: M:R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object,System.Object)
  isExternal: true
  href: R_BlazorFrontEnd.Helpers.R_FrontUtility.html#R_BlazorFrontEnd_Helpers_R_FrontUtility_CompareObject_System_Object_System_Object_
  name: CompareObject(object, object)
  nameWithType: R_FrontUtility.CompareObject(object, object)
  fullName: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(object, object)
  nameWithType.vb: R_FrontUtility.CompareObject(Object, Object)
  fullName.vb: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(Object, Object)
  name.vb: CompareObject(Object, Object)
  spec.csharp:
  - uid: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object,System.Object)
    name: CompareObject
    href: R_BlazorFrontEnd.Helpers.R_FrontUtility.html#R_BlazorFrontEnd_Helpers_R_FrontUtility_CompareObject_System_Object_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object,System.Object)
    name: CompareObject
    href: R_BlazorFrontEnd.Helpers.R_FrontUtility.html#R_BlazorFrontEnd_Helpers_R_FrontUtility_CompareObject_System_Object_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: R_BlazorFrontEnd.Helpers.R_FrontUtility
  commentId: T:R_BlazorFrontEnd.Helpers.R_FrontUtility
  parent: R_BlazorFrontEnd.Helpers
  href: R_BlazorFrontEnd.Helpers.R_FrontUtility.html
  name: R_FrontUtility
  nameWithType: R_FrontUtility
  fullName: R_BlazorFrontEnd.Helpers.R_FrontUtility
- uid: R_BlazorFrontEnd.Extensions
  commentId: N:R_BlazorFrontEnd.Extensions
  href: R_BlazorFrontEnd.html
  name: R_BlazorFrontEnd.Extensions
  nameWithType: R_BlazorFrontEnd.Extensions
  fullName: R_BlazorFrontEnd.Extensions
  spec.csharp:
  - uid: R_BlazorFrontEnd
    name: R_BlazorFrontEnd
    href: R_BlazorFrontEnd.html
  - name: .
  - uid: R_BlazorFrontEnd.Extensions
    name: Extensions
    href: R_BlazorFrontEnd.Extensions.html
  spec.vb:
  - uid: R_BlazorFrontEnd
    name: R_BlazorFrontEnd
    href: R_BlazorFrontEnd.html
  - name: .
  - uid: R_BlazorFrontEnd.Extensions
    name: Extensions
    href: R_BlazorFrontEnd.Extensions.html
- uid: R_BlazorFrontEnd.Helpers
  commentId: N:R_BlazorFrontEnd.Helpers
  href: R_BlazorFrontEnd.html
  name: R_BlazorFrontEnd.Helpers
  nameWithType: R_BlazorFrontEnd.Helpers
  fullName: R_BlazorFrontEnd.Helpers
  spec.csharp:
  - uid: R_BlazorFrontEnd
    name: R_BlazorFrontEnd
    href: R_BlazorFrontEnd.html
  - name: .
  - uid: R_BlazorFrontEnd.Helpers
    name: Helpers
    href: R_BlazorFrontEnd.Helpers.html
  spec.vb:
  - uid: R_BlazorFrontEnd
    name: R_BlazorFrontEnd
    href: R_BlazorFrontEnd.html
  - name: .
  - uid: R_BlazorFrontEnd.Helpers
    name: Helpers
    href: R_BlazorFrontEnd.Helpers.html
- uid: R_BlazorDeployment.R_IResult`1.Data*
  commentId: Overload:R_BlazorDeployment.R_IResult`1.Data
  href: R_BlazorDeployment.R_IResult-1.html#R_BlazorDeployment_R_IResult_1_Data
  name: Data
  nameWithType: R_IResult<T>.Data
  fullName: R_BlazorDeployment.R_IResult<T>.Data
  nameWithType.vb: R_IResult(Of T).Data
  fullName.vb: R_BlazorDeployment.R_IResult(Of T).Data
- uid: '{T}'
  commentId: '!:T'
  definition: T
  name: T
  nameWithType: T
  fullName: T
- uid: T
  name: T
  nameWithType: T
  fullName: T
