### YamlMime:ManagedReference
items:
- uid: R_BlazorDeployment.R_IFileUtility
  commentId: T:R_BlazorDeployment.R_IFileUtility
  id: R_IFileUtility
  parent: R_BlazorDeployment
  children:
  - R_BlazorDeployment.R_IFileUtility.GetFile(System.String)
  - R_BlazorDeployment.R_IFileUtility.SaveFile(System.String,System.Byte[])
  langs:
  - csharp
  - vb
  name: R_IFileUtility
  nameWithType: R_IFileUtility
  fullName: R_BlazorDeployment.R_IFileUtility
  type: Interface
  source:
    remote:
      path: Library Back/R_BlazorDeployment/R_IFileUtility.cs
      branch: master
      repo: git@github.com:siholsihol/RealtaNetCoreLibrary.git
    id: R_IFileUtility
    path: Library Back/R_BlazorDeployment/R_IFileUtility.cs
    startLine: 2
  assemblies:
  - R_BlazorDeployment
  namespace: R_BlazorDeployment
  syntax:
    content: public interface R_IFileUtility
    content.vb: Public Interface R_IFileUtility
  extensionMethods:
  - System.Object.R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull
  - System.Object.R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object)
- uid: R_BlazorDeployment.R_IFileUtility.SaveFile(System.String,System.Byte[])
  commentId: M:R_BlazorDeployment.R_IFileUtility.SaveFile(System.String,System.Byte[])
  id: SaveFile(System.String,System.Byte[])
  parent: R_BlazorDeployment.R_IFileUtility
  langs:
  - csharp
  - vb
  name: SaveFile(string, byte[])
  nameWithType: R_IFileUtility.SaveFile(string, byte[])
  fullName: R_BlazorDeployment.R_IFileUtility.SaveFile(string, byte[])
  type: Method
  source:
    remote:
      path: Library Back/R_BlazorDeployment/R_IFileUtility.cs
      branch: master
      repo: git@github.com:siholsihol/RealtaNetCoreLibrary.git
    id: SaveFile
    path: Library Back/R_BlazorDeployment/R_IFileUtility.cs
    startLine: 4
  assemblies:
  - R_BlazorDeployment
  namespace: R_BlazorDeployment
  syntax:
    content: R_IResult SaveFile(string pcFileName, byte[] poByteFile)
    parameters:
    - id: pcFileName
      type: System.String
    - id: poByteFile
      type: System.Byte[]
    return:
      type: R_BlazorDeployment.R_IResult
    content.vb: Function SaveFile(pcFileName As String, poByteFile As Byte()) As R_IResult
  overload: R_BlazorDeployment.R_IFileUtility.SaveFile*
  nameWithType.vb: R_IFileUtility.SaveFile(String, Byte())
  fullName.vb: R_BlazorDeployment.R_IFileUtility.SaveFile(String, Byte())
  name.vb: SaveFile(String, Byte())
- uid: R_BlazorDeployment.R_IFileUtility.GetFile(System.String)
  commentId: M:R_BlazorDeployment.R_IFileUtility.GetFile(System.String)
  id: GetFile(System.String)
  parent: R_BlazorDeployment.R_IFileUtility
  langs:
  - csharp
  - vb
  name: GetFile(string)
  nameWithType: R_IFileUtility.GetFile(string)
  fullName: R_BlazorDeployment.R_IFileUtility.GetFile(string)
  type: Method
  source:
    remote:
      path: Library Back/R_BlazorDeployment/R_IFileUtility.cs
      branch: master
      repo: git@github.com:siholsihol/RealtaNetCoreLibrary.git
    id: GetFile
    path: Library Back/R_BlazorDeployment/R_IFileUtility.cs
    startLine: 5
  assemblies:
  - R_BlazorDeployment
  namespace: R_BlazorDeployment
  syntax:
    content: R_IResult<byte[]> GetFile(string pcFileName)
    parameters:
    - id: pcFileName
      type: System.String
    return:
      type: R_BlazorDeployment.R_IResult{System.Byte[]}
    content.vb: Function GetFile(pcFileName As String) As R_IResult(Of Byte())
  overload: R_BlazorDeployment.R_IFileUtility.GetFile*
  nameWithType.vb: R_IFileUtility.GetFile(String)
  fullName.vb: R_BlazorDeployment.R_IFileUtility.GetFile(String)
  name.vb: GetFile(String)
references:
- uid: R_BlazorDeployment
  commentId: N:R_BlazorDeployment
  href: R_BlazorDeployment.html
  name: R_BlazorDeployment
  nameWithType: R_BlazorDeployment
  fullName: R_BlazorDeployment
- uid: System.Object.R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull
  commentId: M:R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
  parent: R_BlazorFrontEnd.Extensions.R_FrontExtensions
  definition: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
  href: R_BlazorFrontEnd.Extensions.R_FrontExtensions.html#R_BlazorFrontEnd_Extensions_R_FrontExtensions_ThrowIfNull_System_Object_
  name: ThrowIfNull(object)
  nameWithType: R_FrontExtensions.ThrowIfNull(object)
  fullName: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(object)
  nameWithType.vb: R_FrontExtensions.ThrowIfNull(Object)
  fullName.vb: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(Object)
  name.vb: ThrowIfNull(Object)
  spec.csharp:
  - uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
    name: ThrowIfNull
    href: R_BlazorFrontEnd.Extensions.R_FrontExtensions.html#R_BlazorFrontEnd_Extensions_R_FrontExtensions_ThrowIfNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
    name: ThrowIfNull
    href: R_BlazorFrontEnd.Extensions.R_FrontExtensions.html#R_BlazorFrontEnd_Extensions_R_FrontExtensions_ThrowIfNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object)
  commentId: M:R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object,System.Object)
  parent: R_BlazorFrontEnd.Helpers.R_FrontUtility
  definition: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object,System.Object)
  href: R_BlazorFrontEnd.Helpers.R_FrontUtility.html#R_BlazorFrontEnd_Helpers_R_FrontUtility_CompareObject_System_Object_System_Object_
  name: CompareObject(object, object)
  nameWithType: R_FrontUtility.CompareObject(object, object)
  fullName: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(object, object)
  nameWithType.vb: R_FrontUtility.CompareObject(Object, Object)
  fullName.vb: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(Object, Object)
  name.vb: CompareObject(Object, Object)
  spec.csharp:
  - uid: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object,System.Object)
    name: CompareObject
    href: R_BlazorFrontEnd.Helpers.R_FrontUtility.html#R_BlazorFrontEnd_Helpers_R_FrontUtility_CompareObject_System_Object_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object,System.Object)
    name: CompareObject
    href: R_BlazorFrontEnd.Helpers.R_FrontUtility.html#R_BlazorFrontEnd_Helpers_R_FrontUtility_CompareObject_System_Object_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
  commentId: M:R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
  isExternal: true
  href: R_BlazorFrontEnd.Extensions.R_FrontExtensions.html#R_BlazorFrontEnd_Extensions_R_FrontExtensions_ThrowIfNull_System_Object_
  name: ThrowIfNull(object)
  nameWithType: R_FrontExtensions.ThrowIfNull(object)
  fullName: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(object)
  nameWithType.vb: R_FrontExtensions.ThrowIfNull(Object)
  fullName.vb: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(Object)
  name.vb: ThrowIfNull(Object)
  spec.csharp:
  - uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
    name: ThrowIfNull
    href: R_BlazorFrontEnd.Extensions.R_FrontExtensions.html#R_BlazorFrontEnd_Extensions_R_FrontExtensions_ThrowIfNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
    name: ThrowIfNull
    href: R_BlazorFrontEnd.Extensions.R_FrontExtensions.html#R_BlazorFrontEnd_Extensions_R_FrontExtensions_ThrowIfNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions
  commentId: T:R_BlazorFrontEnd.Extensions.R_FrontExtensions
  parent: R_BlazorFrontEnd.Extensions
  href: R_BlazorFrontEnd.Extensions.R_FrontExtensions.html
  name: R_FrontExtensions
  nameWithType: R_FrontExtensions
  fullName: R_BlazorFrontEnd.Extensions.R_FrontExtensions
- uid: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object,System.Object)
  commentId: M:R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object,System.Object)
  isExternal: true
  href: R_BlazorFrontEnd.Helpers.R_FrontUtility.html#R_BlazorFrontEnd_Helpers_R_FrontUtility_CompareObject_System_Object_System_Object_
  name: CompareObject(object, object)
  nameWithType: R_FrontUtility.CompareObject(object, object)
  fullName: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(object, object)
  nameWithType.vb: R_FrontUtility.CompareObject(Object, Object)
  fullName.vb: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(Object, Object)
  name.vb: CompareObject(Object, Object)
  spec.csharp:
  - uid: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object,System.Object)
    name: CompareObject
    href: R_BlazorFrontEnd.Helpers.R_FrontUtility.html#R_BlazorFrontEnd_Helpers_R_FrontUtility_CompareObject_System_Object_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object,System.Object)
    name: CompareObject
    href: R_BlazorFrontEnd.Helpers.R_FrontUtility.html#R_BlazorFrontEnd_Helpers_R_FrontUtility_CompareObject_System_Object_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: R_BlazorFrontEnd.Helpers.R_FrontUtility
  commentId: T:R_BlazorFrontEnd.Helpers.R_FrontUtility
  parent: R_BlazorFrontEnd.Helpers
  href: R_BlazorFrontEnd.Helpers.R_FrontUtility.html
  name: R_FrontUtility
  nameWithType: R_FrontUtility
  fullName: R_BlazorFrontEnd.Helpers.R_FrontUtility
- uid: R_BlazorFrontEnd.Extensions
  commentId: N:R_BlazorFrontEnd.Extensions
  href: R_BlazorFrontEnd.html
  name: R_BlazorFrontEnd.Extensions
  nameWithType: R_BlazorFrontEnd.Extensions
  fullName: R_BlazorFrontEnd.Extensions
  spec.csharp:
  - uid: R_BlazorFrontEnd
    name: R_BlazorFrontEnd
    href: R_BlazorFrontEnd.html
  - name: .
  - uid: R_BlazorFrontEnd.Extensions
    name: Extensions
    href: R_BlazorFrontEnd.Extensions.html
  spec.vb:
  - uid: R_BlazorFrontEnd
    name: R_BlazorFrontEnd
    href: R_BlazorFrontEnd.html
  - name: .
  - uid: R_BlazorFrontEnd.Extensions
    name: Extensions
    href: R_BlazorFrontEnd.Extensions.html
- uid: R_BlazorFrontEnd.Helpers
  commentId: N:R_BlazorFrontEnd.Helpers
  href: R_BlazorFrontEnd.html
  name: R_BlazorFrontEnd.Helpers
  nameWithType: R_BlazorFrontEnd.Helpers
  fullName: R_BlazorFrontEnd.Helpers
  spec.csharp:
  - uid: R_BlazorFrontEnd
    name: R_BlazorFrontEnd
    href: R_BlazorFrontEnd.html
  - name: .
  - uid: R_BlazorFrontEnd.Helpers
    name: Helpers
    href: R_BlazorFrontEnd.Helpers.html
  spec.vb:
  - uid: R_BlazorFrontEnd
    name: R_BlazorFrontEnd
    href: R_BlazorFrontEnd.html
  - name: .
  - uid: R_BlazorFrontEnd.Helpers
    name: Helpers
    href: R_BlazorFrontEnd.Helpers.html
- uid: R_BlazorDeployment.R_IFileUtility.SaveFile*
  commentId: Overload:R_BlazorDeployment.R_IFileUtility.SaveFile
  href: R_BlazorDeployment.R_IFileUtility.html#R_BlazorDeployment_R_IFileUtility_SaveFile_System_String_System_Byte___
  name: SaveFile
  nameWithType: R_IFileUtility.SaveFile
  fullName: R_BlazorDeployment.R_IFileUtility.SaveFile
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System.Byte[]
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.byte
  name: byte[]
  nameWithType: byte[]
  fullName: byte[]
  nameWithType.vb: Byte()
  fullName.vb: Byte()
  name.vb: Byte()
  spec.csharp:
  - uid: System.Byte
    name: byte
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.byte
  - name: '['
  - name: ']'
  spec.vb:
  - uid: System.Byte
    name: Byte
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.byte
  - name: (
  - name: )
- uid: R_BlazorDeployment.R_IResult
  commentId: T:R_BlazorDeployment.R_IResult
  parent: R_BlazorDeployment
  href: R_BlazorDeployment.R_IResult.html
  name: R_IResult
  nameWithType: R_IResult
  fullName: R_BlazorDeployment.R_IResult
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: R_BlazorDeployment.R_IFileUtility.GetFile*
  commentId: Overload:R_BlazorDeployment.R_IFileUtility.GetFile
  href: R_BlazorDeployment.R_IFileUtility.html#R_BlazorDeployment_R_IFileUtility_GetFile_System_String_
  name: GetFile
  nameWithType: R_IFileUtility.GetFile
  fullName: R_BlazorDeployment.R_IFileUtility.GetFile
- uid: R_BlazorDeployment.R_IResult{System.Byte[]}
  commentId: T:R_BlazorDeployment.R_IResult{System.Byte[]}
  parent: R_BlazorDeployment
  definition: R_BlazorDeployment.R_IResult`1
  href: R_BlazorDeployment.R_IResult-1.html
  name: R_IResult<byte[]>
  nameWithType: R_IResult<byte[]>
  fullName: R_BlazorDeployment.R_IResult<byte[]>
  nameWithType.vb: R_IResult(Of Byte())
  fullName.vb: R_BlazorDeployment.R_IResult(Of Byte())
  name.vb: R_IResult(Of Byte())
  spec.csharp:
  - uid: R_BlazorDeployment.R_IResult`1
    name: R_IResult
    href: R_BlazorDeployment.R_IResult-1.html
  - name: <
  - uid: System.Byte
    name: byte
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.byte
  - name: '['
  - name: ']'
  - name: '>'
  spec.vb:
  - uid: R_BlazorDeployment.R_IResult`1
    name: R_IResult
    href: R_BlazorDeployment.R_IResult-1.html
  - name: (
  - name: Of
  - name: " "
  - uid: System.Byte
    name: Byte
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.byte
  - name: (
  - name: )
  - name: )
- uid: R_BlazorDeployment.R_IResult`1
  commentId: T:R_BlazorDeployment.R_IResult`1
  href: R_BlazorDeployment.R_IResult-1.html
  name: R_IResult<T>
  nameWithType: R_IResult<T>
  fullName: R_BlazorDeployment.R_IResult<T>
  nameWithType.vb: R_IResult(Of T)
  fullName.vb: R_BlazorDeployment.R_IResult(Of T)
  name.vb: R_IResult(Of T)
  spec.csharp:
  - uid: R_BlazorDeployment.R_IResult`1
    name: R_IResult
    href: R_BlazorDeployment.R_IResult-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: R_BlazorDeployment.R_IResult`1
    name: R_IResult
    href: R_BlazorDeployment.R_IResult-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
