### YamlMime:ManagedReference
items:
- uid: R_BlazorFrontEnd.Configurations
  commentId: N:R_BlazorFrontEnd.Configurations
  id: R_BlazorFrontEnd.Configurations
  children:
  - R_BlazorFrontEnd.Configurations.R_FrontConfig
  - R_BlazorFrontEnd.Configurations.R_ServiceUrlSection
  langs:
  - csharp
  - vb
  name: R_BlazorFrontEnd.Configurations
  nameWithType: R_BlazorFrontEnd.Configurations
  fullName: R_BlazorFrontEnd.Configurations
  type: Namespace
  assemblies:
  - R_BlazorFrontEnd
references:
- uid: R_BlazorFrontEnd.Configurations.R_FrontConfig
  commentId: T:R_BlazorFrontEnd.Configurations.R_FrontConfig
  href: R_BlazorFrontEnd.Configurations.R_FrontConfig.html
  name: R_FrontConfig
  nameWithType: R_FrontConfig
  fullName: R_BlazorFrontEnd.Configurations.R_FrontConfig
- uid: R_BlazorFrontEnd.Configurations.R_ServiceUrlSection
  commentId: T:R_BlazorFrontEnd.Configurations.R_ServiceUrlSection
  href: R_BlazorFrontEnd.Configurations.R_ServiceUrlSection.html
  name: R_ServiceUrlSection
  nameWithType: R_ServiceUrlSection
  fullName: R_BlazorFrontEnd.Configurations.R_ServiceUrlSection
