### YamlMime:ManagedReference
items:
- uid: R_BlazorDeployment
  commentId: N:R_BlazorDeployment
  id: R_BlazorDeployment
  children:
  - R_BlazorDeployment.R_IFileUtility
  - R_BlazorDeployment.R_IResult
  - R_BlazorDeployment.R_IResult`1
  - R_BlazorDeployment.R_Result
  - R_BlazorDeployment.R_Result`1
  langs:
  - csharp
  - vb
  name: R_BlazorDeployment
  nameWithType: R_BlazorDeployment
  fullName: R_BlazorDeployment
  type: Namespace
  assemblies:
  - R_BlazorDeployment
references:
- uid: R_BlazorDeployment.R_IFileUtility
  commentId: T:R_BlazorDeployment.R_IFileUtility
  href: R_BlazorDeployment.R_IFileUtility.html
  name: R_IFileUtility
  nameWithType: R_IFileUtility
  fullName: R_BlazorDeployment.R_IFileUtility
- uid: R_BlazorDeployment.R_IResult
  commentId: T:R_BlazorDeployment.R_IResult
  parent: R_BlazorDeployment
  href: R_BlazorDeployment.R_IResult.html
  name: R_IResult
  nameWithType: R_IResult
  fullName: R_BlazorDeployment.R_IResult
- uid: R_BlazorDeployment.R_IResult`1
  commentId: T:R_BlazorDeployment.R_IResult`1
  href: R_BlazorDeployment.R_IResult-1.html
  name: R_IResult<T>
  nameWithType: R_IResult<T>
  fullName: R_BlazorDeployment.R_IResult<T>
  nameWithType.vb: R_IResult(Of T)
  fullName.vb: R_BlazorDeployment.R_IResult(Of T)
  name.vb: R_IResult(Of T)
  spec.csharp:
  - uid: R_BlazorDeployment.R_IResult`1
    name: R_IResult
    href: R_BlazorDeployment.R_IResult-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: R_BlazorDeployment.R_IResult`1
    name: R_IResult
    href: R_BlazorDeployment.R_IResult-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: R_BlazorDeployment.R_Result
  commentId: T:R_BlazorDeployment.R_Result
  parent: R_BlazorDeployment
  href: R_BlazorDeployment.R_Result.html
  name: R_Result
  nameWithType: R_Result
  fullName: R_BlazorDeployment.R_Result
- uid: R_BlazorDeployment.R_Result`1
  commentId: T:R_BlazorDeployment.R_Result`1
  parent: R_BlazorDeployment
  href: R_BlazorDeployment.R_Result-1.html
  name: R_Result<T>
  nameWithType: R_Result<T>
  fullName: R_BlazorDeployment.R_Result<T>
  nameWithType.vb: R_Result(Of T)
  fullName.vb: R_BlazorDeployment.R_Result(Of T)
  name.vb: R_Result(Of T)
  spec.csharp:
  - uid: R_BlazorDeployment.R_Result`1
    name: R_Result
    href: R_BlazorDeployment.R_Result-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: R_BlazorDeployment.R_Result`1
    name: R_Result
    href: R_BlazorDeployment.R_Result-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: R_BlazorDeployment
  commentId: N:R_BlazorDeployment
  href: R_BlazorDeployment.html
  name: R_BlazorDeployment
  nameWithType: R_BlazorDeployment
  fullName: R_BlazorDeployment
