### YamlMime:ManagedReference
items:
- uid: R_BlazorFrontEnd.Interfaces.R_IEnvironment
  commentId: T:R_BlazorFrontEnd.Interfaces.R_IEnvironment
  id: R_IEnvironment
  parent: R_BlazorFrontEnd.Interfaces
  children:
  - R_BlazorFrontEnd.Interfaces.R_IEnvironment.EnvironmentName
  - R_BlazorFrontEnd.Interfaces.R_IEnvironment.IsDevelopment
  - R_BlazorFrontEnd.Interfaces.R_IEnvironment.IsProduction
  - R_BlazorFrontEnd.Interfaces.R_IEnvironment.IsStaging
  langs:
  - csharp
  - vb
  name: R_IEnvironment
  nameWithType: R_IEnvironment
  fullName: R_BlazorFrontEnd.Interfaces.R_IEnvironment
  type: Interface
  source:
    remote:
      path: Library/R_BlazorFrontEnd/Interfaces/R_IEnvironment.cs
      branch: master
      repo: git@github.com:siholsihol/RealtaNetCoreLibrary.git
    id: R_IEnvironment
    path: Library/R_BlazorFrontEnd/Interfaces/R_IEnvironment.cs
    startLine: 2
  assemblies:
  - R_BlazorFrontEnd
  namespace: R_BlazorFrontEnd.Interfaces
  syntax:
    content: public interface R_IEnvironment
    content.vb: Public Interface R_IEnvironment
  extensionMethods:
  - System.Object.R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull
  - System.Object.R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object)
- uid: R_BlazorFrontEnd.Interfaces.R_IEnvironment.EnvironmentName
  commentId: P:R_BlazorFrontEnd.Interfaces.R_IEnvironment.EnvironmentName
  id: EnvironmentName
  parent: R_BlazorFrontEnd.Interfaces.R_IEnvironment
  langs:
  - csharp
  - vb
  name: EnvironmentName
  nameWithType: R_IEnvironment.EnvironmentName
  fullName: R_BlazorFrontEnd.Interfaces.R_IEnvironment.EnvironmentName
  type: Property
  source:
    remote:
      path: Library/R_BlazorFrontEnd/Interfaces/R_IEnvironment.cs
      branch: master
      repo: git@github.com:siholsihol/RealtaNetCoreLibrary.git
    id: EnvironmentName
    path: Library/R_BlazorFrontEnd/Interfaces/R_IEnvironment.cs
    startLine: 4
  assemblies:
  - R_BlazorFrontEnd
  namespace: R_BlazorFrontEnd.Interfaces
  syntax:
    content: string EnvironmentName { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property EnvironmentName As String
  overload: R_BlazorFrontEnd.Interfaces.R_IEnvironment.EnvironmentName*
- uid: R_BlazorFrontEnd.Interfaces.R_IEnvironment.IsDevelopment
  commentId: P:R_BlazorFrontEnd.Interfaces.R_IEnvironment.IsDevelopment
  id: IsDevelopment
  parent: R_BlazorFrontEnd.Interfaces.R_IEnvironment
  langs:
  - csharp
  - vb
  name: IsDevelopment
  nameWithType: R_IEnvironment.IsDevelopment
  fullName: R_BlazorFrontEnd.Interfaces.R_IEnvironment.IsDevelopment
  type: Property
  source:
    remote:
      path: Library/R_BlazorFrontEnd/Interfaces/R_IEnvironment.cs
      branch: master
      repo: git@github.com:siholsihol/RealtaNetCoreLibrary.git
    id: IsDevelopment
    path: Library/R_BlazorFrontEnd/Interfaces/R_IEnvironment.cs
    startLine: 5
  assemblies:
  - R_BlazorFrontEnd
  namespace: R_BlazorFrontEnd.Interfaces
  syntax:
    content: bool IsDevelopment { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: ReadOnly Property IsDevelopment As Boolean
  overload: R_BlazorFrontEnd.Interfaces.R_IEnvironment.IsDevelopment*
- uid: R_BlazorFrontEnd.Interfaces.R_IEnvironment.IsStaging
  commentId: P:R_BlazorFrontEnd.Interfaces.R_IEnvironment.IsStaging
  id: IsStaging
  parent: R_BlazorFrontEnd.Interfaces.R_IEnvironment
  langs:
  - csharp
  - vb
  name: IsStaging
  nameWithType: R_IEnvironment.IsStaging
  fullName: R_BlazorFrontEnd.Interfaces.R_IEnvironment.IsStaging
  type: Property
  source:
    remote:
      path: Library/R_BlazorFrontEnd/Interfaces/R_IEnvironment.cs
      branch: master
      repo: git@github.com:siholsihol/RealtaNetCoreLibrary.git
    id: IsStaging
    path: Library/R_BlazorFrontEnd/Interfaces/R_IEnvironment.cs
    startLine: 6
  assemblies:
  - R_BlazorFrontEnd
  namespace: R_BlazorFrontEnd.Interfaces
  syntax:
    content: bool IsStaging { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: ReadOnly Property IsStaging As Boolean
  overload: R_BlazorFrontEnd.Interfaces.R_IEnvironment.IsStaging*
- uid: R_BlazorFrontEnd.Interfaces.R_IEnvironment.IsProduction
  commentId: P:R_BlazorFrontEnd.Interfaces.R_IEnvironment.IsProduction
  id: IsProduction
  parent: R_BlazorFrontEnd.Interfaces.R_IEnvironment
  langs:
  - csharp
  - vb
  name: IsProduction
  nameWithType: R_IEnvironment.IsProduction
  fullName: R_BlazorFrontEnd.Interfaces.R_IEnvironment.IsProduction
  type: Property
  source:
    remote:
      path: Library/R_BlazorFrontEnd/Interfaces/R_IEnvironment.cs
      branch: master
      repo: git@github.com:siholsihol/RealtaNetCoreLibrary.git
    id: IsProduction
    path: Library/R_BlazorFrontEnd/Interfaces/R_IEnvironment.cs
    startLine: 7
  assemblies:
  - R_BlazorFrontEnd
  namespace: R_BlazorFrontEnd.Interfaces
  syntax:
    content: bool IsProduction { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: ReadOnly Property IsProduction As Boolean
  overload: R_BlazorFrontEnd.Interfaces.R_IEnvironment.IsProduction*
references:
- uid: R_BlazorFrontEnd.Interfaces
  commentId: N:R_BlazorFrontEnd.Interfaces
  href: R_BlazorFrontEnd.html
  name: R_BlazorFrontEnd.Interfaces
  nameWithType: R_BlazorFrontEnd.Interfaces
  fullName: R_BlazorFrontEnd.Interfaces
  spec.csharp:
  - uid: R_BlazorFrontEnd
    name: R_BlazorFrontEnd
    href: R_BlazorFrontEnd.html
  - name: .
  - uid: R_BlazorFrontEnd.Interfaces
    name: Interfaces
    href: R_BlazorFrontEnd.Interfaces.html
  spec.vb:
  - uid: R_BlazorFrontEnd
    name: R_BlazorFrontEnd
    href: R_BlazorFrontEnd.html
  - name: .
  - uid: R_BlazorFrontEnd.Interfaces
    name: Interfaces
    href: R_BlazorFrontEnd.Interfaces.html
- uid: System.Object.R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull
  commentId: M:R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
  parent: R_BlazorFrontEnd.Extensions.R_FrontExtensions
  definition: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
  href: R_BlazorFrontEnd.Extensions.R_FrontExtensions.html#R_BlazorFrontEnd_Extensions_R_FrontExtensions_ThrowIfNull_System_Object_
  name: ThrowIfNull(object)
  nameWithType: R_FrontExtensions.ThrowIfNull(object)
  fullName: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(object)
  nameWithType.vb: R_FrontExtensions.ThrowIfNull(Object)
  fullName.vb: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(Object)
  name.vb: ThrowIfNull(Object)
  spec.csharp:
  - uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
    name: ThrowIfNull
    href: R_BlazorFrontEnd.Extensions.R_FrontExtensions.html#R_BlazorFrontEnd_Extensions_R_FrontExtensions_ThrowIfNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
    name: ThrowIfNull
    href: R_BlazorFrontEnd.Extensions.R_FrontExtensions.html#R_BlazorFrontEnd_Extensions_R_FrontExtensions_ThrowIfNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object)
  commentId: M:R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object,System.Object)
  parent: R_BlazorFrontEnd.Helpers.R_FrontUtility
  definition: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object,System.Object)
  href: R_BlazorFrontEnd.Helpers.R_FrontUtility.html#R_BlazorFrontEnd_Helpers_R_FrontUtility_CompareObject_System_Object_System_Object_
  name: CompareObject(object, object)
  nameWithType: R_FrontUtility.CompareObject(object, object)
  fullName: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(object, object)
  nameWithType.vb: R_FrontUtility.CompareObject(Object, Object)
  fullName.vb: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(Object, Object)
  name.vb: CompareObject(Object, Object)
  spec.csharp:
  - uid: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object,System.Object)
    name: CompareObject
    href: R_BlazorFrontEnd.Helpers.R_FrontUtility.html#R_BlazorFrontEnd_Helpers_R_FrontUtility_CompareObject_System_Object_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object,System.Object)
    name: CompareObject
    href: R_BlazorFrontEnd.Helpers.R_FrontUtility.html#R_BlazorFrontEnd_Helpers_R_FrontUtility_CompareObject_System_Object_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
  commentId: M:R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
  isExternal: true
  href: R_BlazorFrontEnd.Extensions.R_FrontExtensions.html#R_BlazorFrontEnd_Extensions_R_FrontExtensions_ThrowIfNull_System_Object_
  name: ThrowIfNull(object)
  nameWithType: R_FrontExtensions.ThrowIfNull(object)
  fullName: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(object)
  nameWithType.vb: R_FrontExtensions.ThrowIfNull(Object)
  fullName.vb: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(Object)
  name.vb: ThrowIfNull(Object)
  spec.csharp:
  - uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
    name: ThrowIfNull
    href: R_BlazorFrontEnd.Extensions.R_FrontExtensions.html#R_BlazorFrontEnd_Extensions_R_FrontExtensions_ThrowIfNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
    name: ThrowIfNull
    href: R_BlazorFrontEnd.Extensions.R_FrontExtensions.html#R_BlazorFrontEnd_Extensions_R_FrontExtensions_ThrowIfNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions
  commentId: T:R_BlazorFrontEnd.Extensions.R_FrontExtensions
  parent: R_BlazorFrontEnd.Extensions
  href: R_BlazorFrontEnd.Extensions.R_FrontExtensions.html
  name: R_FrontExtensions
  nameWithType: R_FrontExtensions
  fullName: R_BlazorFrontEnd.Extensions.R_FrontExtensions
- uid: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object,System.Object)
  commentId: M:R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object,System.Object)
  isExternal: true
  href: R_BlazorFrontEnd.Helpers.R_FrontUtility.html#R_BlazorFrontEnd_Helpers_R_FrontUtility_CompareObject_System_Object_System_Object_
  name: CompareObject(object, object)
  nameWithType: R_FrontUtility.CompareObject(object, object)
  fullName: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(object, object)
  nameWithType.vb: R_FrontUtility.CompareObject(Object, Object)
  fullName.vb: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(Object, Object)
  name.vb: CompareObject(Object, Object)
  spec.csharp:
  - uid: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object,System.Object)
    name: CompareObject
    href: R_BlazorFrontEnd.Helpers.R_FrontUtility.html#R_BlazorFrontEnd_Helpers_R_FrontUtility_CompareObject_System_Object_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: R_BlazorFrontEnd.Helpers.R_FrontUtility.CompareObject(System.Object,System.Object)
    name: CompareObject
    href: R_BlazorFrontEnd.Helpers.R_FrontUtility.html#R_BlazorFrontEnd_Helpers_R_FrontUtility_CompareObject_System_Object_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: R_BlazorFrontEnd.Helpers.R_FrontUtility
  commentId: T:R_BlazorFrontEnd.Helpers.R_FrontUtility
  parent: R_BlazorFrontEnd.Helpers
  href: R_BlazorFrontEnd.Helpers.R_FrontUtility.html
  name: R_FrontUtility
  nameWithType: R_FrontUtility
  fullName: R_BlazorFrontEnd.Helpers.R_FrontUtility
- uid: R_BlazorFrontEnd.Extensions
  commentId: N:R_BlazorFrontEnd.Extensions
  href: R_BlazorFrontEnd.html
  name: R_BlazorFrontEnd.Extensions
  nameWithType: R_BlazorFrontEnd.Extensions
  fullName: R_BlazorFrontEnd.Extensions
  spec.csharp:
  - uid: R_BlazorFrontEnd
    name: R_BlazorFrontEnd
    href: R_BlazorFrontEnd.html
  - name: .
  - uid: R_BlazorFrontEnd.Extensions
    name: Extensions
    href: R_BlazorFrontEnd.Extensions.html
  spec.vb:
  - uid: R_BlazorFrontEnd
    name: R_BlazorFrontEnd
    href: R_BlazorFrontEnd.html
  - name: .
  - uid: R_BlazorFrontEnd.Extensions
    name: Extensions
    href: R_BlazorFrontEnd.Extensions.html
- uid: R_BlazorFrontEnd.Helpers
  commentId: N:R_BlazorFrontEnd.Helpers
  href: R_BlazorFrontEnd.html
  name: R_BlazorFrontEnd.Helpers
  nameWithType: R_BlazorFrontEnd.Helpers
  fullName: R_BlazorFrontEnd.Helpers
  spec.csharp:
  - uid: R_BlazorFrontEnd
    name: R_BlazorFrontEnd
    href: R_BlazorFrontEnd.html
  - name: .
  - uid: R_BlazorFrontEnd.Helpers
    name: Helpers
    href: R_BlazorFrontEnd.Helpers.html
  spec.vb:
  - uid: R_BlazorFrontEnd
    name: R_BlazorFrontEnd
    href: R_BlazorFrontEnd.html
  - name: .
  - uid: R_BlazorFrontEnd.Helpers
    name: Helpers
    href: R_BlazorFrontEnd.Helpers.html
- uid: R_BlazorFrontEnd.Interfaces.R_IEnvironment.EnvironmentName*
  commentId: Overload:R_BlazorFrontEnd.Interfaces.R_IEnvironment.EnvironmentName
  href: R_BlazorFrontEnd.Interfaces.R_IEnvironment.html#R_BlazorFrontEnd_Interfaces_R_IEnvironment_EnvironmentName
  name: EnvironmentName
  nameWithType: R_IEnvironment.EnvironmentName
  fullName: R_BlazorFrontEnd.Interfaces.R_IEnvironment.EnvironmentName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: R_BlazorFrontEnd.Interfaces.R_IEnvironment.IsDevelopment*
  commentId: Overload:R_BlazorFrontEnd.Interfaces.R_IEnvironment.IsDevelopment
  href: R_BlazorFrontEnd.Interfaces.R_IEnvironment.html#R_BlazorFrontEnd_Interfaces_R_IEnvironment_IsDevelopment
  name: IsDevelopment
  nameWithType: R_IEnvironment.IsDevelopment
  fullName: R_BlazorFrontEnd.Interfaces.R_IEnvironment.IsDevelopment
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: R_BlazorFrontEnd.Interfaces.R_IEnvironment.IsStaging*
  commentId: Overload:R_BlazorFrontEnd.Interfaces.R_IEnvironment.IsStaging
  href: R_BlazorFrontEnd.Interfaces.R_IEnvironment.html#R_BlazorFrontEnd_Interfaces_R_IEnvironment_IsStaging
  name: IsStaging
  nameWithType: R_IEnvironment.IsStaging
  fullName: R_BlazorFrontEnd.Interfaces.R_IEnvironment.IsStaging
- uid: R_BlazorFrontEnd.Interfaces.R_IEnvironment.IsProduction*
  commentId: Overload:R_BlazorFrontEnd.Interfaces.R_IEnvironment.IsProduction
  href: R_BlazorFrontEnd.Interfaces.R_IEnvironment.html#R_BlazorFrontEnd_Interfaces_R_IEnvironment_IsProduction
  name: IsProduction
  nameWithType: R_IEnvironment.IsProduction
  fullName: R_BlazorFrontEnd.Interfaces.R_IEnvironment.IsProduction
