### YamlMime:ManagedReference
items:
- uid: R_BlazorFrontEnd.Controls.Deployment
  commentId: N:R_BlazorFrontEnd.Controls.Deployment
  id: R_BlazorFrontEnd.Controls.Deployment
  children:
  - R_BlazorFrontEnd.Controls.Deployment.R_AssemblyDataProvider
  - R_BlazorFrontEnd.Controls.Deployment.R_AssemblyLoadContext
  - R_BlazorFrontEnd.Controls.Deployment.R_DynamicAssetProviderService
  langs:
  - csharp
  - vb
  name: R_BlazorFrontEnd.Controls.Deployment
  nameWithType: R_BlazorFrontEnd.Controls.Deployment
  fullName: R_BlazorFrontEnd.Controls.Deployment
  type: Namespace
  assemblies:
  - R_BlazorFrontEnd.Controls
references:
- uid: R_BlazorFrontEnd.Controls.Deployment.R_AssemblyDataProvider
  commentId: T:R_BlazorFrontEnd.Controls.Deployment.R_AssemblyDataProvider
  href: R_BlazorFrontEnd.Controls.Deployment.R_AssemblyDataProvider.html
  name: R_AssemblyDataProvider
  nameWithType: R_AssemblyDataProvider
  fullName: R_BlazorFrontEnd.Controls.Deployment.R_AssemblyDataProvider
- uid: R_BlazorFrontEnd.Controls.Deployment.R_AssemblyLoadContext
  commentId: T:R_BlazorFrontEnd.Controls.Deployment.R_AssemblyLoadContext
  href: R_BlazorFrontEnd.Controls.Deployment.R_AssemblyLoadContext.html
  name: R_AssemblyLoadContext
  nameWithType: R_AssemblyLoadContext
  fullName: R_BlazorFrontEnd.Controls.Deployment.R_AssemblyLoadContext
- uid: R_BlazorFrontEnd.Controls.Deployment.R_DynamicAssetProviderService
  commentId: T:R_BlazorFrontEnd.Controls.Deployment.R_DynamicAssetProviderService
  href: R_BlazorFrontEnd.Controls.Deployment.R_DynamicAssetProviderService.html
  name: R_DynamicAssetProviderService
  nameWithType: R_DynamicAssetProviderService
  fullName: R_BlazorFrontEnd.Controls.Deployment.R_DynamicAssetProviderService
