### YamlMime:ManagedReference
items:
- uid: R_ReportServerClient.DTO.R_ReportServerClientConfiguration
  commentId: T:R_ReportServerClient.DTO.R_ReportServerClientConfiguration
  id: R_ReportServerClientConfiguration
  parent: R_ReportServerClient.DTO
  children:
  - R_ReportServerClient.DTO.R_ReportServerClientConfiguration.MaximumBatchThread
  - R_ReportServerClient.DTO.R_ReportServerClientConfiguration.MinimumBatchThread
  - R_ReportServerClient.DTO.R_ReportServerClientConfiguration.ReportServerUrl
  - R_ReportServerClient.DTO.R_ReportServerClientConfiguration.TimeOutInMinutes
  langs:
  - csharp
  - vb
  name: R_ReportServerClientConfiguration
  nameWithType: R_ReportServerClientConfiguration
  fullName: R_ReportServerClient.DTO.R_ReportServerClientConfiguration
  type: Class
  source:
    remote:
      path: Microservices/R_ReportServerClient/DTO/R_ReportServerClientConfiguration.cs
      branch: master
      repo: git@github.com:siholsihol/RealtaLibrary.git
    id: R_ReportServerClientConfiguration
    path: Microservices/R_ReportServerClient/DTO/R_ReportServerClientConfiguration.cs
    startLine: 8
  assemblies:
  - R_ReportServerClient
  namespace: R_ReportServerClient.DTO
  syntax:
    content: 'public class R_ReportServerClientConfiguration : object'
    content.vb: >-
      Public Class R_ReportServerClientConfiguration
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: R_ReportServerClient.DTO.R_ReportServerClientConfiguration.ReportServerUrl
  commentId: P:R_ReportServerClient.DTO.R_ReportServerClientConfiguration.ReportServerUrl
  id: ReportServerUrl
  parent: R_ReportServerClient.DTO.R_ReportServerClientConfiguration
  langs:
  - csharp
  - vb
  name: ReportServerUrl
  nameWithType: R_ReportServerClientConfiguration.ReportServerUrl
  fullName: R_ReportServerClient.DTO.R_ReportServerClientConfiguration.ReportServerUrl
  type: Property
  source:
    remote:
      path: Microservices/R_ReportServerClient/DTO/R_ReportServerClientConfiguration.cs
      branch: master
      repo: git@github.com:siholsihol/RealtaLibrary.git
    id: ReportServerUrl
    path: Microservices/R_ReportServerClient/DTO/R_ReportServerClientConfiguration.cs
    startLine: 10
  assemblies:
  - R_ReportServerClient
  namespace: R_ReportServerClient.DTO
  syntax:
    content: public string ReportServerUrl { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ReportServerUrl As String
  overload: R_ReportServerClient.DTO.R_ReportServerClientConfiguration.ReportServerUrl*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: R_ReportServerClient.DTO.R_ReportServerClientConfiguration.TimeOutInMinutes
  commentId: P:R_ReportServerClient.DTO.R_ReportServerClientConfiguration.TimeOutInMinutes
  id: TimeOutInMinutes
  parent: R_ReportServerClient.DTO.R_ReportServerClientConfiguration
  langs:
  - csharp
  - vb
  name: TimeOutInMinutes
  nameWithType: R_ReportServerClientConfiguration.TimeOutInMinutes
  fullName: R_ReportServerClient.DTO.R_ReportServerClientConfiguration.TimeOutInMinutes
  type: Property
  source:
    remote:
      path: Microservices/R_ReportServerClient/DTO/R_ReportServerClientConfiguration.cs
      branch: master
      repo: git@github.com:siholsihol/RealtaLibrary.git
    id: TimeOutInMinutes
    path: Microservices/R_ReportServerClient/DTO/R_ReportServerClientConfiguration.cs
    startLine: 11
  assemblies:
  - R_ReportServerClient
  namespace: R_ReportServerClient.DTO
  syntax:
    content: public int TimeOutInMinutes { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property TimeOutInMinutes As Integer
  overload: R_ReportServerClient.DTO.R_ReportServerClientConfiguration.TimeOutInMinutes*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: R_ReportServerClient.DTO.R_ReportServerClientConfiguration.MinimumBatchThread
  commentId: P:R_ReportServerClient.DTO.R_ReportServerClientConfiguration.MinimumBatchThread
  id: MinimumBatchThread
  parent: R_ReportServerClient.DTO.R_ReportServerClientConfiguration
  langs:
  - csharp
  - vb
  name: MinimumBatchThread
  nameWithType: R_ReportServerClientConfiguration.MinimumBatchThread
  fullName: R_ReportServerClient.DTO.R_ReportServerClientConfiguration.MinimumBatchThread
  type: Property
  source:
    remote:
      path: Microservices/R_ReportServerClient/DTO/R_ReportServerClientConfiguration.cs
      branch: master
      repo: git@github.com:siholsihol/RealtaLibrary.git
    id: MinimumBatchThread
    path: Microservices/R_ReportServerClient/DTO/R_ReportServerClientConfiguration.cs
    startLine: 12
  assemblies:
  - R_ReportServerClient
  namespace: R_ReportServerClient.DTO
  syntax:
    content: public int MinimumBatchThread { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property MinimumBatchThread As Integer
  overload: R_ReportServerClient.DTO.R_ReportServerClientConfiguration.MinimumBatchThread*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: R_ReportServerClient.DTO.R_ReportServerClientConfiguration.MaximumBatchThread
  commentId: P:R_ReportServerClient.DTO.R_ReportServerClientConfiguration.MaximumBatchThread
  id: MaximumBatchThread
  parent: R_ReportServerClient.DTO.R_ReportServerClientConfiguration
  langs:
  - csharp
  - vb
  name: MaximumBatchThread
  nameWithType: R_ReportServerClientConfiguration.MaximumBatchThread
  fullName: R_ReportServerClient.DTO.R_ReportServerClientConfiguration.MaximumBatchThread
  type: Property
  source:
    remote:
      path: Microservices/R_ReportServerClient/DTO/R_ReportServerClientConfiguration.cs
      branch: master
      repo: git@github.com:siholsihol/RealtaLibrary.git
    id: MaximumBatchThread
    path: Microservices/R_ReportServerClient/DTO/R_ReportServerClientConfiguration.cs
    startLine: 13
  assemblies:
  - R_ReportServerClient
  namespace: R_ReportServerClient.DTO
  syntax:
    content: public int MaximumBatchThread { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property MaximumBatchThread As Integer
  overload: R_ReportServerClient.DTO.R_ReportServerClientConfiguration.MaximumBatchThread*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: R_ReportServerClient.DTO
  commentId: N:R_ReportServerClient.DTO
  name: R_ReportServerClient.DTO
  nameWithType: R_ReportServerClient.DTO
  fullName: R_ReportServerClient.DTO
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: R_ReportServerClient.DTO.R_ReportServerClientConfiguration.ReportServerUrl*
  commentId: Overload:R_ReportServerClient.DTO.R_ReportServerClientConfiguration.ReportServerUrl
  name: ReportServerUrl
  nameWithType: R_ReportServerClientConfiguration.ReportServerUrl
  fullName: R_ReportServerClient.DTO.R_ReportServerClientConfiguration.ReportServerUrl
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: R_ReportServerClient.DTO.R_ReportServerClientConfiguration.TimeOutInMinutes*
  commentId: Overload:R_ReportServerClient.DTO.R_ReportServerClientConfiguration.TimeOutInMinutes
  name: TimeOutInMinutes
  nameWithType: R_ReportServerClientConfiguration.TimeOutInMinutes
  fullName: R_ReportServerClient.DTO.R_ReportServerClientConfiguration.TimeOutInMinutes
- uid: System.Int32
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: R_ReportServerClient.DTO.R_ReportServerClientConfiguration.MinimumBatchThread*
  commentId: Overload:R_ReportServerClient.DTO.R_ReportServerClientConfiguration.MinimumBatchThread
  name: MinimumBatchThread
  nameWithType: R_ReportServerClientConfiguration.MinimumBatchThread
  fullName: R_ReportServerClient.DTO.R_ReportServerClientConfiguration.MinimumBatchThread
- uid: R_ReportServerClient.DTO.R_ReportServerClientConfiguration.MaximumBatchThread*
  commentId: Overload:R_ReportServerClient.DTO.R_ReportServerClientConfiguration.MaximumBatchThread
  name: MaximumBatchThread
  nameWithType: R_ReportServerClientConfiguration.MaximumBatchThread
  fullName: R_ReportServerClient.DTO.R_ReportServerClientConfiguration.MaximumBatchThread
